### ISSUE TITLE
Issues with blur-my-shell application blur

### ISSUE THREAD

**Issue by hexxt-git** [flexagoon/rounded-window-corners#11]
I installed this extension recently and it works pretty well. besides for most things i use daily, mainly: vscode, spotify, chromium and discord.
I don't know if this is a configuration or installation issue on my side or if its a limitation of gnome extensions, either way I'm still searching for a solution

**Comment by flexagoon** [comment]
All of the apps you listed are Chromium/Electron, so I guess it somehow breaks stuff. I'll look into it. Though it works with Logseq for me, which is also written in Electron.

**Comment by flexagoon** [comment]
I am not able to reproduce this issue with Spotify. How do you install and launch those apps? And how did you install the extension?

**Comment by GrzegorzKozub** [comment]
For me it works with Visual Studio Code and Brave (a Chromium browser). At least on Xorg. Didn't check Wayland yet.

**Comment by adityainduraj** [comment]
On Wayland Gnome 46, the extension works perfectly on VSCode, Obsidian, and chromium browsers like Brave/Chromium.

**Comment by 9EED** [comment]
so i got it working but not fully. i think the issue is a conflict with "blur my shell" i have that extension to also blur applications. it wont round the corners until i turn it off then on

[Screencast from 2024-05-12 08-15-48.webm](https://github.com/flexagoon/rounded-window-corners/assets/88392191/47a281d2-1ab3-4d37-b521-27e2ad0833b5)


I am on arch and gnome 46, i installed the extension through gnome-extensions install on the zip file and install my apps from pacman and flatpak

**Comment by flexagoon** [comment]
@9EED could you check if the issue still happens if you disable application blur in blur-my-shell?

**Comment by adityainduraj** [comment]
@9EED Yes, I think the issue is only there with blur-my-shell. I said it was working perfectly for me, but I'm not using the Blur-My-Shell extension.

**Comment by 9EED** [comment]
@flexagoon the issue goes away if i disable application blur

**Comment by 9EED** [comment]
i also found that this ugly border shows up randomly and i cant figure out how to reliably replicate it

![image](https://github.com/flexagoon/rounded-window-corners/assets/88392191/6754136c-e385-4606-92a7-e887eb06593f)

**Comment by GrzegorzKozub** [comment]
With recent Brave update to version 1.67 I started seeing the transparent frame and that frame is what's getting the rounded corners while the actual Brave corners remain unchanged. No issues with other apps I use, like Visual Studio Code for example.

![image](https://github.com/flexagoon/rounded-window-corners/assets/154056/fad7fe52-11b7-402e-826a-4f371fd6df87)

**Comment by SiraMirai** [comment]
Adding to this, I recently updated my Vesktop client (build it from source so that screensharing works properly for me) and unless I disable the window frame it it's settings I get this same border issue there as well. Spotify and other electron apps I use dont have this issue

**Comment by gaurishmehra** [comment]
any updates on this???

**Comment by ryzendew** [comment]
@aunetx not sure if you know or not but maybe you can help

**Comment by flexagoon** [comment]
https://github.com/aunetx/blur-my-shell/issues/634#issuecomment-2351086715

**Comment by Schneegans** [comment]
If you want to, you could try #77 and tell me if this works for you!
