### ISSUE TITLE
/usr/bin/env: ‘node’: Text file busy

### ISSUE THREAD

**Issue by linzeennnn** [flexagoon/rounded-window-corners#17]
when i run 
`yarn ext:install`
i get this error
```
yarn run v1.22.22
$ gulp install
/usr/bin/env: ‘node’: Text file busy
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
![2024-05-22_22-38](https://github.com/flexagoon/rounded-window-corners/assets/152974252/a46231f2-76d9-4471-af46-080590a3dc4c)

**Comment by flexagoon** [comment]
Please see the installation instructions in the readme. `yarn ext:install` is the old installation method and it will no longer work.
