### ISSUE TITLE
Rounded Window Corners Extension Not Appearing in Extensions App

### ISSUE THREAD

**Issue by VictorAseo** [flexagoon/rounded-window-corners#19]
I recently installed the Rounded Window Corners extension on my device, but unfortunately, it does not appear in the extensions app. I followed the installation process carefully, and it seemed to complete successfully. However, when I open the extensions app, I can't find Rounded Window Corners listed there. I've tried restarting my device and checking for any updates, but the issue persists. I'm not sure what went wrong or what steps I should take to resolve this.

![image](https://github.com/flexagoon/rounded-window-corners/assets/66032954/edacdf44-2ac9-440e-a874-13dd3d4d0793)

![image](https://github.com/flexagoon/rounded-window-corners/assets/66032954/42785d3b-b10d-4d5b-b8d4-0b84e3eb1baf)

**Comment by iamkartiksingh-K** [comment]
Try restarting your laptop.

**Comment by flexagoon** [comment]
Check the `~/.local/share/gnome-shell/extensions` folder. Is it installed there?

The extension will also be available on Gnome Extensions soon, the blur-my-shell version that was blocking the release is already published, so I'll publish this extension when I finish with school exams

**Comment by VictorAseo** [comment]
Yeah, it worked. Thank you so much!

The corners of my Hyper.is were not rounded, and it was driving me crazy. Hahaha. Thank you so much!
