### ISSUE TITLE
Latest workflow run download link not clickable

### ISSUE THREAD

**Issue by delta1071** [flexagoon/rounded-window-corners#23]
I tried the download link in Firefox 126 and Chromium Browser 125.

**Comment by delta1071** [comment]
Forgot to mention I tried the download link in Firefox 126 and Chromium Browser 125.

**Comment by flexagoon** [comment]
I am able to click the link just fine. Are you sure you're logged into your GitHub account when trying to click the link?

**Comment by delta1071** [comment]
Can you see how red my face is? I didn't realize I had to sign in to Github first, SO, you can close this issue. Thanks for responding.

**Comment by flexagoon** [comment]
@delta1071 it's fine, it's on me for not mentioning this in the readme. There's #20 which is supposed to fix this, though it has a typo which the author didn't fix yet, so I'll probably just add this information myself
