### ISSUE TITLE
Issue with Blur My Shell (Applications blur) for some apps

### ISSUE THREAD

**Issue by stoneC0der** [flexagoon/rounded-window-corners#25]
Up until Gnome 44 with the original extension I never had the issue below.

Now currently on Gnome 46, Kali 2024, kernel 6.6.9, Xorg

- When I manually install the extension, logout & back in
- The windows are not rounded, so after disabling/enabling blur my shell the windows are now rounded.
- But when I tried to launch some app, like Terninator (terminal), I just see the shadow of the app itself, but does not fully load.

In the screenshot below you can see a blurred windows, the size is actually smaller than the blur part

![Screenshot from 2024-06-25 15-46-42](https://github.com/flexagoon/rounded-window-corners/assets/11365636/c239eceb-8c88-4bcc-afc8-d40cff0ed8fe)

Here is after disabling application window blur on Terminator, Gnome terminal work fine, so I guess it is some apps that is not working properly when both blur my shell & RWC are enabled.

![Screenshot from 2024-06-25 15-52-46](https://github.com/flexagoon/rounded-window-corners/assets/11365636/f4718493-109c-448d-98d7-1c0901277fb4)

Some of the apps I tried so far, that fail to display are:

- Terminator
- Postman
- Dbeaver
- Transmission (flatpak)
- WhatSie (flatpak)
- Vlc 

Working fine:

- Vscode (not properly rounded)
- Firefox ESR
- PhpStorm (not properly rounded)

Excluding the app from application blur is the workaround that I using. But I can leave with that for Terminator, but everything else I like it blur, but also appreciate this extension.
I guess I will have to compromise for now, some apps blur, and those having issue, I exclude them from Blur My Shell.

I will also try to tweak both Blur My Shell Application blur setting as well as RWC application shadow and see.

**Comment by flexagoon** [comment]
See #11
