### ISSUE TITLE
Top corners are pixelated for certain windows.

### ISSUE THREAD

**Issue by in4matix** [flexagoon/rounded-window-corners#28]
Ah! I'm so glad that this project has a new maintainer. Thank you so much!

The issue that I am experiencing is that some legacy applications, which I have quite many of, all have pixelated top corners. The bottom corners are aces though. If you maybe get the time to have a look, it will be much appreciated as my organization will not be upgrading to Ubuntu 24 anytime soon.

My system is Ubuntu 22.04 LTS (Gnome 42.9)

Screenshot:

![Screenshot from 2024-06-28 16-00-03](https://github.com/flexagoon/rounded-window-corners/assets/62904593/5a2cb0ce-d354-46a1-94e5-c5e2d6d1e971)

Do you accept donations? I will be more than happy to contribute financially as I can't write code. Too stupid :-)

BTW, the extension works perfectly in a Ubuntu 24 VM.

**Comment by flexagoon** [comment]
> My system is Ubuntu 22.04 LTS (Gnome 42.9)
> ...
> the extension works perfectly in a Ubuntu 24 VM.

I don't think there's anything I could do  in that case? This fork had some breaking changes and it only supports GNOME 46+, so even if I fixed the bug you wouldn't be able to benefit from it.

I can still try to investigate the cause though, maybe it indicates a different issue with the extension.

Could you please provide the following information:

- Does the issue happen under X11 or Wayland?
- If it's under Wayland, is the affected application running natively or through Xwayland?
- Please share your settings for this extension (just a screenshot of the settings page should be enough?

> Do you accept donations? I will be more than happy to contribute financially as I can't write code.

I'd be happy to, but I live in Russia, so it isn't possible for me to accept any international transfers. I can accept crypto if that's an option for you and you want to donate.

**Comment by in4matix** [comment]
> Does the issue happen under X11 or Wayland?

Wayland

> If it's under Wayland, is the affected application running natively or through Xwayland?

Here are a few that I opened, but have many others, but xlclients does not seem to list Appimages and Binaries:

```
daniel@dkdt:~$ xlsclients
dkdt  gsd-xsettings
dkdt  ibus-x11
dkdt  gnome-shell
dkdt  thunderbird-esr
dkdt  rdc
daniel@dkdt:~$
```

> Are the corners still pixelated if you disable the extension?

With the extension disabled, the top corners are slightly less rounded but no pixelation.

> Please share your settings for this extension (just a screenshot of the settings page should be enough?

![Screenshot from 2024-06-28 17-31-24](https://github.com/flexagoon/rounded-window-corners/assets/62904593/76b6c570-6c77-45b3-a153-d9f1e917523c)

All settings are at default. I have not changed anything.

![Screenshot from 2024-06-28 17-30-31](https://github.com/flexagoon/rounded-window-corners/assets/62904593/e875d9a3-106f-42f9-b4e2-9d04a96c013f)

> I'd be happy to, but I live in Russia, so it isn't possible for me to accept any international transfers. I can accept crypto if that's an option for you and you want to donate.

I'm in South Africa. I don't have any crypto, but have been wanting to try it out. I will post back here when I have something set-up.
