### ISSUE TITLE
Windows don't display properly in overview after updating Mutter

### ISSUE THREAD

**Issue by Gulang233** [flexagoon/rounded-window-corners#29]
Screenshots (click the pictures to open them in new tabs):
|Screenshot1|Extension enabled and Chrome is not maximized (note the lower left and lower right corners of the window)|This window is not maximized but is very large|The window of LibreOffice Writer is maximized|Same as above, but with "keep rounded corners for maximized windows" on
|:---:|:---:|:---:|:---:|:---:|
|![Screenshot1](https://github.com/flexagoon/rounded-window-corners/assets/59766725/bcfcab45-59b7-462e-bb5d-d2893f371fa4)|![Extension enabled and Chrome is not maximized](https://github.com/flexagoon/rounded-window-corners/assets/59766725/9bb60ce7-9352-4560-98dd-c8c61834ccc7)|![This window is not maximized but is very large](https://github.com/flexagoon/rounded-window-corners/assets/59766725/21d712d6-26ed-4a73-a32f-3d1193cae566)|![The window of LibreOffice Writer is maximized](https://github.com/flexagoon/rounded-window-corners/assets/59766725/f63a4d78-11e7-47a7-ab6b-24ee87d7d25f)|![Same as above, but with "keep rounded corners for maximized windows" on](https://github.com/flexagoon/rounded-window-corners/assets/59766725/0ca69b65-805f-41b3-800a-535d7ee347a4)

This happened after updating Mutter.

As shown in screenshot1, when there are multiple windows in a workspace, the left and top of the windows will be cut off.
~If there's only one window in the workspace~ If the window is not enlarged or reduced, the window will not be cut off. (But in "overwiew", GTK3 windows will only have rounded corners on top left and top right corners)

I turned off "skip LibAdwaita applications" and "skip LibHandy applications", so LibAdwaita and LibHandy app windows will be cut off, too. If I turn them on, LibAdwaita and LibHandy app windows will not be cut off, but old GTK3 windows like Google Chrome or LibreOffice will be cut off.

BTW maximized or fullscreen windows won't be cut off, too. No matter I turn on "keep rounded corners for maximized windows" or "keep rounded corners for fullscreen windows" or not.

Here's some system information that may help:
- OS: Arch Linux
- Kernel: Linux 6.9.7-zen1-1-zen
- DE: Gnome 46.3.1
- WM: Mutter 46.3.1
- Window system: Wayland
- Extension version: 2 from extensions.gnome.org

**Comment by MisTerio497** [comment]
I would recommend that you roll back using the downgrade program
[https://github.com/archlinux-downgrade/downgrade](url)

**Comment by Gulang233** [comment]
Thank you for recommending, @MisTerio497 !
I just tried downgrading Mutter from 46.3<b>.1-1</b> to 46.3<b>-1</b> by installing the old package from [Arch Linux Rollback Machine](https://wiki.archlinux.org/title/Arch_Linux_Archive), and the windows in overview are no longer cut off, for now, if I don't upgrade Mutter.
However, this bug still needs to be fixed, and I would be happy to upgrade Mutter again to provide more information to fix this bug.

**Comment by Gulang233** [comment]
BTW [here](https://gitlab.gnome.org/GNOME/mutter/-/tags/46.3.1)'s the changelog of Mutter 46.3.1:
> 46.3.1
> ======
> * Fix visibility of Xwayland windows [[Michel; !3862]](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3862)
> * Misc. bug fixes [[Marco; !2959]](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2959)
> 
> Contributors:
>   Michel Dänzer, Marco Trevisan (Treviño)

**Comment by Froztmuffins** [comment]
Same on Fedora 40 Wayland

**Comment by LSeelig** [comment]
Same issue on Fedora 40 Wayland. I think it was also called by mutter update.
[Screencast from 2024-07-09 17-14-22 (trimmed).webm](https://github.com/flexagoon/rounded-window-corners/assets/37001137/5752cd9d-80ec-4320-a12e-2fbfebd27a2e)

**Comment by LSeelig** [comment]
Could an option be added to disable rounded window corners in the overview until there is a fix?

**Comment by flexagoon** [comment]
@LSeelig I'm playing around with the codebase, and it seems like this can be solved very easily at the expense of having overview windows be slightly blurry. I'm still trying to find a solution without this tradeoff though.
