### ISSUE TITLE
[BUG] This plugin will cause compiz-alike-magic-lamp-effect animation bug, is there a way to solve it?

### ISSUE THREAD

**Issue by mike2635** [flexagoon/rounded-window-corners#32]
This plugin will cause compiz-alike-magic-lamp-effect animation bug, is there a way to solve it?

**Comment by flexagoon** [comment]
What's the bug?

**Comment by mike2635** [comment]
> What's the bug?

Animated bugs like shown in the video, I hope you can help analyze and solve it, thank you!


https://github.com/user-attachments/assets/fc1348e9-aaa6-4866-8ecf-c6db968eb2a3

**Comment by k2helix** [comment]
Disabling opacity in shadow preferences seems to solve it
