### ISSUE TITLE
Schema doesn't get updated when updating the extension

### ISSUE THREAD

**Issue by yochananmarqos** [flexagoon/rounded-window-corners#44]
GNOME 46.5 on Arch Stable / Manjaro Unstable from the latest commit f3b78cb:

```
TypeError: this._cfg.keepRoundedCorners is undefined

Stack trace:
  @file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
  pages@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

It works fine from commit 439a9e3.

**Comment by myth5** [comment]
i have the same issue
disable the extension and remove it then unpack the latest zip file and move it to /usr/share/gnome-shell/extensions

**Comment by yochananmarqos** [comment]
@flexagoon I've updated the issue to include more info.

**Comment by flexagoon** [comment]
@yochananmarqos that still doesn't answer my question. How did you install the extension?

**Comment by yochananmarqos** [comment]
@flexagoon Oh, sorry. I'm using the `gnome-shell-extension-rounded-window-corners-reborn-git` AUR package.

**Comment by flexagoon** [comment]
Not sure why this happens. I asked on the gnome discourse, waiting for someone to help

https://discourse.gnome.org/t/why-doesnt-the-gsettings-schema-update-with-the-extension/23478

**Comment by flexagoon** [comment]
@yochananmarqos @eisregenhaha can you please run this command and tell the output?

`gsettings get org.gnome.shell.extensions.rounded-window-corners-reborn settings-version`

**Comment by EisregenHaha** [comment]
> @yochananmarqos @EisregenHaha can you please run this command and tell the output?
> 
> `gsettings get org.gnome.shell.extensions.rounded-window-corners-reborn settings-version`

its telling me that there is no such schema when i install the extension from actions. 

`No such schema “org.gnome.shell.extensions.rounded-window-corners-reborn”`

i also tried installing it from source and got the same result, completely deleting and logging out the extension before each attempt.

**Comment by yochananmarqos** [comment]
@flexagoon I think you probably know the answer. Either way, it's the same with both commits I mentioned: `uint32 5`

**Comment by yochananmarqos** [comment]
By the way, I just tested f3b78cb via `gnome-shell-extension-rounded-window-corners-reborn-git` on GNOME 47 and can no longer reproduce it. Feel free to close this issue at your discretion.

**Comment by yochananmarqos** [comment]
@flexagoon I can reproduce again. I have no idea why. Please reopen the issue.

```
TypeError: this._cfg.keepRoundedCorners is undefined

Stack trace:
  @file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:45
  pages@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:39:24
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:15:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:138:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

```

**Comment by EisregenHaha** [comment]
> @flexagoon I can reproduce again. I have no idea why. Please reopen the issue.
> 
> ```
> TypeError: this._cfg.keepRoundedCorners is undefined
> 
> Stack trace:
>   @file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:45
>   pages@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
>   fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
>   _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:39:24
>   async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:14
>   ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:15:4
>   OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:138:33
>   async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
>   _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
>   _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
> ```

i cant reproduce anymore, build it from source. has been fixed for me since weeks. no reason to reopen

**Comment by yochananmarqos** [comment]
@EisregenHaha Alright, I'll do some more investigation. I understand it's quite odd that it's happening again.
