### ISSUE TITLE
Plz update for gnome 47 im begging you

### ISSUE THREAD

**Issue by EisregenHaha** [flexagoon/rounded-window-corners#45]
i love ur work and this extension so much my desktop is unusable without it plz update im on my knees. this time i cant offer feet pics tho because you will actually do it

**Comment by flexagoon** [comment]
The latest commit already supports gnome 47, you can install it from GitHub actions using instructions in the readme. It just needs a few minor changes to pass EGO review.

**Comment by flexagoon** [comment]
Also there were no breaking changes in Gnome 47, so even if you don't install the git version the latest release should just work with `gsettings set org.gnome.shell disable-extension-version-validation true`

**Comment by EisregenHaha** [comment]
> Also there were no breaking changes in Gnome 47, so even if you don't install the git version the latest release should just work with `gsettings set org.gnome.shell disable-extension-version-validation true`

ah thanks man, didnt think to try for the same reasons u listed

**Comment by EisregenHaha** [comment]
> Also there were no breaking changes in Gnome 47, so even if you don't install the git version the latest release should just work with `gsettings set org.gnome.shell disable-extension-version-validation true`

so i just built it from source but the corners wont turn round? im on the fedora 41 beta and they just stay square

**Comment by flexagoon** [comment]
> so i just built it from source but the corners wont turn round? im on the fedora 41 beta and they just stay square and i get this error when trying to open the extension settings

Yeah, that's exactly why I said to install it from GitHub actions instead of building from source

**Comment by flexagoon** [comment]
Please try installing it using `gnome-extensions install` and then tell me if the error still happens. I changed the settings schema a bit and it's supposed to automatically migrate, but it doesn't do that in some cases. It's fine if that only happens when building from source, but I want to know if it also happens with regular installation.

**Comment by EisregenHaha** [comment]
> Please try installing it using `gnome-extensions install` and then tell me if the error still happens. I changed the settings schema a bit and it's supposed to automatically migrate, but it doesn't do that in some cases. It's fine if that only happens when building from source, but I want to know if it also happens with regular installation.

so yeah i just installed using actions and the same issue persists, i tried clean installing (dk if that makes a diff) but everything i tried leads to the same result.

**Comment by radical4ever** [comment]
> Please try installing it using `gnome-extensions install` and then tell me if the error still happens. I changed the settings schema a bit and it's supposed to automatically migrate, but it doesn't do that in some cases. It's fine if that only happens when building from source, but I want to know if it also happens with regular installation.

tried the same thing, on regular install and got the same issue

**Comment by flexagoon** [comment]
#44

**Comment by Neo-29** [comment]
needs AUR update

if you're in touch with packager/maintainer
