### ISSUE TITLE
Port to GNOME 47

### ISSUE THREAD

**Issue by human-V-oid** [flexagoon/rounded-window-corners#47]
Since GNOME 47 has been released, I request an update to add compatibility.
There is a guide at: [Port Extensions to GNOME Shell 47 ](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

**Comment by flexagoon** [comment]
#44

**Comment by cbrnr** [comment]
I think when people are asking for GNOME 47 support, they are referring to the extension not being available on https://extensions.gnome.org/. It seems like the last two submitted versions were rejected (https://extensions.gnome.org/review/57807), but I guess you are already working on fixing those and submitting a new version?

**Comment by flexagoon** [comment]
@cbrnr those issues are pretty trivial to fix, the bigger issue is #44

**Comment by cbrnr** [comment]
Got it, thanks @flexagoon!
