### ISSUE TITLE
Can't add to the Blacklist

### ISSUE THREAD

**Issue by Aurailus** [flexagoon/rounded-window-corners#5]
Hi! First of all, thank you for forking this extension to work with GNOME 46! I love rounded corners and I already use adwgtk3 for my non LibAdwaita applications, and it's really nice to have proper rounded corners on those applications as well.
I'm running into an issue where starting guvcview while this extension is enabled crashes GNOME. No problem, I thought, I'd just blacklist it. But when I go into the Blacklist tab and press Add Window, nothing happens. No popup, no text entry field, nothing. I know the WM_CLASS of the window, but I have no idea where to put it. Inspecting the extension in dconf-editor, I couldn't find a blacklist property, either. I was hoping that this could be patched, or I could be told where to manually enter into the blacklist so I can keep using this extension. I'm using the latest artifact from Github Actions.
Thanks!!

(also I have a really cursed font installed, please disregard)
![image](https://github.com/flexagoon/rounded-window-corners/assets/22041561/e5852f8e-427e-4f02-bf4c-3267ab555104)

**Comment by flexagoon** [comment]
> I'm running into an issue where starting guvcview while this extension is enabled crashes GNOME.

Uhh I don't think that's supposed to happen. Could you please attach Gnome logs? Though I don't know if it's an issue with the extension or an upstream Gnome issue.

> But when I go into the Blacklist tab and press Add Window, nothing happens

Maybe I missed something in https://github.com/flexagoon/rounded-window-corners/commit/f620bd238876037833195182c1d7a199fddc310f. I'll look into it.

> I have a really cursed font installed

why

**Comment by Aurailus** [comment]
> Uhh I don't think that's supposed to happen. Could you please attach Gnome logs? Though I don't know if it's an issue with the extension or an upstream Gnome issue.
What directory would I find those in? Do I need to enable something to have it create logs, and then cause the crash again?
> why
I don't like people looking over my shoulder and seeing what I'm reading/writing.

**Comment by flexagoon** [comment]
> What directory would I find those in?

They're just regular logs, you can see them with `journalctl /usr/bin/gnome-shell`

> I don't like people looking over my shoulder and seeing what I'm reading/writing.

Yes but how do you read the font yourself?

**Comment by flexagoon** [comment]
I'm still interested in the font thing though. Is it a custom thing you did for yourself or a public font? If it's public, is there somewhere I can read about it?

**Comment by Aurailus** [comment]
I based it off of Sans Forgetica, which is a font you can download which is all split up into little pieces. Then, over the course of a week, I gradually removed more pieces from each letter, and jumbled some of the shapes around. Because I was the one doing it and I gave myself time to adjust every time, I'm still able to read it. I'm happy to share the font files with you if you want, it's no big secret (people could just reverse engineer it from looking at enough screenshots. I'm just trying to stop casual onlookers from snooping on me)

**Comment by Aurailus** [comment]
Also, thanks for the bugfix!

**Comment by flexagoon** [comment]
@Aurailus 
> I'm happy to share the font files with you if you want

Thanks for offering, but I don't think it would be of much use to me, as the main place where I'd want that font is when texting with someone, and the font doesn't seem to support Cyrillic letters.

Interesting nonetheless, I might do something like that myself in the future!
