### ISSUE TITLE
 rounded-window-corners is messing with blur my shell

### ISSUE THREAD

**Issue by githlacker** [flexagoon/rounded-window-corners#56]
without **rounded-window-corners**:
![image](https://github.com/user-attachments/assets/3eb66cb7-c1ca-45c7-905c-631a069a7147)

with **rounded-window-corners**:
![image](https://github.com/user-attachments/assets/b44262c3-3307-4326-8854-4c22dd74b541)

**Comment by flexagoon** [comment]
https://github.com/aunetx/blur-my-shell/issues/634#issuecomment-2351086715

**Comment by Schneegans** [comment]
If you want to, you could try #77 and tell me if this works for you!
