### ISSUE TITLE
[bug] Rounded corner is not happening when i restart the device

### ISSUE THREAD

**Issue by satrujit11** [flexagoon/rounded-window-corners#59]
## System Specification:
- Gnome 46
- Fedora

## Issue
When I restart my device, it is not keeping the rounded corner. I have to manually turn off and turn on to the extension for it to make it rounded again.

https://github.com/user-attachments/assets/1cea66c4-d429-41b8-85a2-b9b586c1ab52

**Comment by flexagoon** [comment]
I can't reproduce this on my end. Can you record a video of this happening (maybe record your screen with your phone, just make sure it's clear what's going on)

**Comment by satrujit11** [comment]
Sure. I am adding the video to it

**Comment by flexagoon** [comment]
@satrujit11 can you please check if this still happens?

**Comment by satrujit11** [comment]
@flexagoon  The bug is resolved.
Thank you.
