### ISSUE TITLE
Ghost shadows/transparent window after closing windows

### ISSUE THREAD

**Issue by DWolf-19** [flexagoon/rounded-window-corners#6]
```
OS: Fedora 40
WM: Wayland
RWC: latest GitHub Actions build
```

Here's what happened after closing the calculator (for instance):
![image](https://github.com/flexagoon/rounded-window-corners/assets/108197792/5c4d6bb8-280c-4a45-8a59-e0c0ac076dcb)

Debug with calculator (`journalctl -o cat -f /usr/bin/gnome-shell`):
```
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
JS ERROR: too much recursion
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
get@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/conveniences/settings.js:51:59
_log@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/overview.js:202:13
enable/wac_proto._prepareWorkspaceSwitch@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/overview.js:65:28

[A bunch of duplicated lines]:
enable/WorkspaceAnimationController.prototype._prepareWorkspaceSwitch@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/extension.js:163:47
enable/wac_proto._prepareWorkspaceSwitch@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/overview.js:66:52

...

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Object .MetaWindowActorWayland (0x56054d720400), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56054c5cbac0 ==
#0   7ffc580fb060 b   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/rounded_corners_manager.js:165 (9b4ab2127e0 @ 31)
#1   56054c692170 i   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:148 (213042330380 @ 15)
#2   7ffc580fbb10 b   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:19 (9b4ab2e8470 @ 90)
#3   56054c6920e8 i   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:148 (213042330060 @ 17)
#4   56054c692058 i   resource:///org/gnome/shell/ui/init.js:21 (3e086fc70bf0 @ 48)
JS ERROR: TypeError: win is null
on_focus_changed@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/rounded_corners_manager.js:170:33
_add_effect/actor_is_ready/</<@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:148:33
run@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:19:17
_add_effect/actor_is_ready/<@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:148:22
@resource:///org/gnome/shell/ui/init.js:21:20

Object .MetaWindowActorWayland (0x56054d720400), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56054c5cbac0 ==
#0   7ffc580fb260 b   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/rounded_corners_manager.js:165 (9b4ab2127e0 @ 31)
#1   56054c692170 i   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:153 (213042336330 @ 15)
#2   7ffc580fbd10 b   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:19 (9b4ab2e8470 @ 90)
#3   56054c6920e8 i   file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:153 (213042330b50 @ 17)
#4   56054c692058 i   resource:///org/gnome/shell/ui/init.js:21 (3e086fc70bf0 @ 48)
JS ERROR: TypeError: win is null
on_focus_changed@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/rounded_corners_manager.js:170:33
_add_effect/actor_is_ready/</<@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:153:33
run@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:19:17
_add_effect/actor_is_ready/<@file:///home/dwolfnineteen/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/manager/effect_manager.js:153:22
@resource:///org/gnome/shell/ui/init.js:21:20
```

I think it related to https://github.com/yilozt/rounded-window-corners/issues/129

**Comment by flexagoon** [comment]
When does this happen for you? Is it every time you close any window?

**Comment by DWolf-19** [comment]
Yes

**Comment by flexagoon** [comment]
I can't reproduce this on the latest commit. What other extensions do you have installed? Can you disable them and check if this still occurs?

**Comment by DWolf-19** [comment]
This is my extension list:
![image](https://github.com/flexagoon/rounded-window-corners/assets/108197792/afac8034-430c-4690-9a3c-5dfe3d306c70)

I've been experimenting a bit. Problem is reproduced with all disabled extensions except RWC. 

At some point, this stopped happening after disabling and then enabling Blur my Shell, but after scrolling through spaces with the mouse this bug is back (_I have another one bug, I was able to reproduce it even by turning off all extensions 🤔, and I don't know if it belongs to RWC: on my desktop it is impossible to swipe spaces with the mouse wheel by pointing at the indicator_
![image](https://github.com/flexagoon/rounded-window-corners/assets/108197792/f2999988-63a4-4fbc-98ae-68c07c9091d8)
_I can only do this after pressing `Super` and then switch workspace_). 

I can't reproduce the above (with restarting Blur my Shell) a second time and so far I don't see any logic at what point something breaks.

Maybe I can try to log out in GNOME after each turn on/off RWC and Blur my Shell and see what happens... idk

**Comment by flexagoon** [comment]
Could you please try turning off all extensions except RWC and then restarting Gnome Shell? Also, do you have the latest version of Blur My Shell (61)?

**Comment by flexagoon** [comment]
The blur my shell issue might be caused by some other extension also conflicting with it and is fixed by https://github.com/aunetx/blur-my-shell/pull/588, so it'll be fixed with the next blur my shell release

**Comment by DWolf-19** [comment]
I lied a little bit, I had build 3a1ec4e4d87be9ecfcfe4f33c72fcdb8790776e9 installed and now I've upgraded to 6d0504de727bf590d202f1a99a648b9e89dd692d and it just got fixed (*I hope*)...  It seemed to me that the last commit had nothing to do with my bug and therefore did not update immediately. 

I'll also check everything later to make sure it works.

Thanks 🌙

**Comment by flexagoon** [comment]
So is this issue completely resolved for you now?

**Comment by DWolf-19** [comment]
Yeah, it looks like bug fixed. Thank you!

**Comment by Myned** [comment]
I'm experiencing this problem as well, and I vaguely recall it happening with the original extension pre-fork which was [supposed to be fixed](https://github.com/yilozt/rounded-window-corners/issues/55). Currently using the version of this fork that is in review for the [GNOME extension store](https://extensions.gnome.org/review/55303) on NixOS unstable. I don't use Blur My Shell and it happens with only Rounded Window Corners Reborn enabled.

It is reproducible by:
1. Open Firefox's Picture-in-Picture mode on a video
2. Move PiP window to a different workspace
3. Close PiP by clicking the "Back to tab" button, which switches to the starting workspace
4. Observe the PiP window's residual shadow in the top left corner of the display

The residual shadow can be cleared by opening and closing the GNOME Overview (Super key by default).

FWIW, this doesn't occur with Chromium's PiP window, but has happened unreproducibly with other applications in my case. It seems directly related to workspace switching.

It wouldn't fix the issue, but I would prefer the default shadows anyways, so perhaps a toggle to disable the custom shadows would suffice for those experiencing this issue.

**Comment by flexagoon** [comment]
> It wouldn't fix the issue, but I would prefer the default shadows anyways, so perhaps a toggle to disable the custom shadows would suffice for those experiencing this issue.

@Myned this wouldn't work, because the default shadows don't have rounded corners. So you'll have a rounded window with a square shadow.

**Comment by Myned** [comment]
Ah, gotcha. Though, the default shadows are barely noticeable on a white background and are fairly blurred in general, so it may be functional enough as a stopgap solution.

Is there a way to use Libadwaita/GTK4's shadows? Those windows usually have rounded corners, just wouldn't necessarily match the extension settings.
