### ISSUE TITLE
I'm locking this since it's an upstream issue and it's up to Gnome to fix this

### ISSUE THREAD

**Issue by Neo-29** [flexagoon/rounded-window-corners#68]
I'm locking this since it's an upstream issue and it's up to Gnome to fix this

@aunetx please ping me somewhere else if you find a way to work around this

_Originally posted by @flexagoon in https://github.com/flexagoon/rounded-window-corners/issues/36#issuecomment-2358872466_

**Comment by Neo-29** [comment]
Any news of that?

Best regards

**Comment by flexagoon** [comment]
There is a link to the upstream GNOME bug report in that issue. I can't do anything about it. You should ask GNOME maintainers on their issue tracker.

**Comment by Neo-29** [comment]
> There is a link to the upstream GNOME bug report in that issue. I can't do anything about it. You should ask GNOME maintainers on their issue tracker.

Nobody answers there.. So..
What else can I do?

**Comment by flexagoon** [comment]
I don't know. You can ping a maintainer there or write a fix and submit it yourself. I'm not related to that issue in any way and I can't help you with it, please don't ask me about it since I can't do anything
