### ISSUE TITLE
мне не понравилось 

### ISSUE THREAD

**Issue by Ultrageopro1966** [flexagoon/rounded-window-corners#7]
хуета полная

**Comment by flexagoon** [comment]
удали компьютер

**Comment by Ultrageopro1966** [comment]
> удали компьютер

слышь оболтус соси попу я гит мегасеньор а ты всего лишь пешка в мире опенсурса я главный дев а ты лузер хахаха линукс ядрышко проверь

**Comment by flexagoon** [comment]
🙁 дружище не круто ... .. За что ты так ........

**Comment by Ultrageopro1966** [comment]
> 🙁 дружище не круто ... .. За что ты так ........

![IMG_20240506_151913_471.png](https://github.com/flexagoon/rounded-window-corners/assets/120571667/8218d134-5abf-4048-b0bc-5ebca7e1e6c2)

хахаха это буквально ты не понимаешь мой хитрый план по захвату опенсурса ахахаха боже какие вы все людишки отсталые думаете вы дев хахаха нет это я дев

**Comment by flexagoon** [comment]
ааааа черт подери твой план пришел в действо все шестерёнки в твоём хитром веретене пара и стали завертелись в точно выверенном танце и последствия воплотились в жизнь 😭 теперь ты владелец этого репозитория исходного когда а также всего сообщества свободного программного обеспечения ...... ..

**Comment by Ultrageopro1966** [comment]
> ааааа черт подери твой план пришел в действо все шестерёнки в твоём хитром веретене пара и стали завертелись в точно выверенном танце и последствия воплотились в жизнь 😭 теперь ты владелец этого репозитория исходного когда а также всего сообщества свободного программного обеспечения ...... .. 

ммм я чувствую страх в этом сообщении мммм о да ммм бойтесь меня дев девелоперы хахах егнеба боров первый поп... ммм.. хех.. ляшет.

**Comment by Ultrageopro1966** [comment]
нет скорее они будут выглядеть примерно так или около того

![Screenshot_20240503_231503_Telegram.jpg](https://github.com/flexagoon/rounded-window-corners/assets/120571667/3eca0ad4-5484-49bf-b5a9-90aefae9680e)

![images (4).jpeg](https://github.com/flexagoon/rounded-window-corners/assets/120571667/70df451e-7768-4c0b-8833-27f2a6373792)

![IMG_20240505_175943_481.jpg](https://github.com/flexagoon/rounded-window-corners/assets/120571667/5644307f-4094-44dc-8eab-a07cf8f17866)

**Comment by Ultrageopro1966** [comment]
блять

**Comment by Ultrageopro1966** [comment]
короче вот так они выглядеть будут когда увидят это обсуждение 

Uploading 2_5283275954125292353.MOV …

хахаха тупые людишки опенсурс почитатели поверили в этот пранк хахахаха как бы не так снова ваш мастер кукловод попатрах ультрагеопро вас надурил хехе

**Comment by flexagoon** [comment]
мастер куколд в потрохах ультрагеочмо 🤣
