### ISSUE TITLE
Make it compatable with compiz window effects gnome extension

### ISSUE THREAD

**Issue by BlueFox1616** [flexagoon/rounded-window-corners#72]
[Screencast From 2024-12-18 15-18-19.webm](https://github.com/user-attachments/assets/656fd52f-81fa-487b-89ac-cfd59ed450b1)
What the tittle says and video for reference :

**Comment by BlueFox1616** [comment]
it looks like there is a transparent border but it doesn't follow the movement off the app and cuts it out

**Comment by flexagoon** [comment]
#14
