### ISSUE TITLE
Gnome Shell Extension

### ISSUE THREAD

**Issue by sudarshancode** [flexagoon/rounded-window-corners#8]
Plz upload this in gnome shell extension

**Comment by sudarshancode** [comment]
and I can not finding uuid

**Comment by flexagoon** [comment]
This extension currently has a workaround to avoid a bug with blur-my-shell. It can't be uploaded to Gnome Extensions with this workaround. When the next version of Blur My Shell gets released, the workaround will no longer be needed, and I will publish the extension.

**Comment by flexagoon** [comment]
This extension currently has a workaround to avoid a bug with blur-my-shell. It can't be uploaded to Gnome Extensions with this workaround. When the next version of Blur My Shell gets released, the workaround will no longer be needed, and I will publish the extension @sudarshancode

**Comment by Tommimon** [comment]
A [new version](https://github.com/aunetx/blur-my-shell/releases/tag/v62) of blur-my-shell was released last weak. Can you upload it to Gnome Extensions now?

**Comment by flexagoon** [comment]
@Tommimon I already did, it's currently under review

https://extensions.gnome.org/review/55303

**Comment by Poly2it** [comment]
> @Tommimon I already did, it's currently under review
> 
> https://extensions.gnome.org/review/55303

It was rejected just now with 11 mentioned issues @flexagoon.

**Comment by Tommimon** [comment]
Thanks! It is now available on GNOME shell extensions website [here](https://extensions.gnome.org/extension/7048/rounded-window-corners-reborn/).
